[package]
name = "delivery"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.14.0"
axum = "0.8.4"
sqlx = "0.8.6"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
